# Generated by Django 3.2 on 2022-02-23 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='play',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='play',
            name='help',
        ),
        migrations.AlterField(
            model_name='play',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
